=== hinaaptech/CRUD_XMl/XMLSchema1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema  
    xmlns:xs="http://www.w3.org/2001/XMLSchema"   
>
  <xs:element name="Employees" >
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Employee" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
            

              <xs:element name="Id">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1" />
                    <xs:maxInclusive value="20" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>


              <xs:element name="Name">
                <xs:simpleType>
                  <xs:restriction base="xs:string">              
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>


              <xs:element name="Mobile">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[0-4]{4}-[0-9]{7}" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>


              <xs:element name="City">
                <xs:simpleType>
                  <xs:restriction base="xs:string" />

                </xs:simpleType>
              </xs:element>

              <xs:element name="Country">
                <xs:simpleType>
                  <xs:restriction base="xs:string" />                         
                </xs:simpleType>
              </xs:element>



            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>



</xs:schema>

=== hinaaptech/CRUD_XMl/Employee.xml
<?xml version="1.0" standalone="yes"?>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchema1.xsd">
  <Employee>
    <Id>1</Id>
    <Name>ahmed</Name>
    <Mobile>0300-1234567</Mobile>
    <City>Islamabad</City>
    <Country>Pakistan</Country>
  </Employee>
  <Employee>
    <Id>2</Id>
    <Name>Asshad</Name>
    <Mobile>0300-1239876</Mobile>
    <City>Multan</City>
    <Country>Pakistan</Country>
  </Employee>
  <Employee>
    <Id>3</Id>
    <Name>Danish</Name>
    <Mobile>0301-1231235</Mobile>
    <City>Newyork</City>
    <Country>America</Country>
  </Employee>
  <Employee>
    <Id>4</Id>
    <Name>James</Name>
    <Mobile>0332-2018190</Mobile>
    <City>Ankara</City>
    <Country>Turkey</Country>
  </Employee>
  <Employee>
    <Id>5</Id>
    <Name>Ali</Name>
    <Mobile>0300-1234547</Mobile>
    <City>Istanbul</City>
    <Country>Turkey</Country>
  </Employee>
  <Employee>
    <Id>3</Id>
    <Name>John</Name>
    <Mobile>0301-7654321</Mobile>
    <City>Toranto</City>
    <Country>Canada</Country>
  </Employee>
  <Employee>
    <Name>sajida</Name>
    <Mobile>0300-1234567</Mobile>
    <City>karachi</City>
    <Country>pka</Country>
  </Employee>
</Employees>
